### ISSUE TITLE
NoSuchMethodError with 1.3.0

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#72]
```
java.lang.NoSuchMethodError: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.hasLabel([Ljava/lang/String;)Lorg/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal;
	at org.umlg.sqlg.structure.SchemaManager.loadUserSchema(SchemaManager.java:1305)
	at org.umlg.sqlg.structure.SchemaManager.loadSchema(SchemaManager.java:1042)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:218)

```
When I run a project getting 1.3.0 from Maven. I'll build from source and see, but maybe the project has not been properly cleaned and rebuilt.

**Comment by maximmi** [comment]
Same issue for me
Worked well with 1.2.0, updating to 1.3.0 gives same java.lang.NoSuchMethodError

**Comment by JPMoresmau** [comment]
I've rebuilt from source and it works fine.

**Comment by pietermartin** [comment]
Hi,
Don't know what happened there. A colleague of mine also just got it. Its almost as thought the class files are compiled to the wrong jvm version with `mvn deploy`

I'll need to investigate and redeploy once I get what went wrong.

**Comment by metlos** [comment]
Basically, Tinkerpop made an incompatible API change between in 3.2.2. I reported it here: https://issues.apache.org/jira/browse/TINKERPOP-1443

**Comment by pietermartin** [comment]
Yeah, I still don't understand how I managed to deploy a incorrect artifact.
`mvn clean deploy -P release` for sure recompiles everything.

Anyhow I released `1.3.2` tested and this time it seems fine.

**Comment by JPMoresmau** [comment]
1.3.2? The github release page stops at 1.3.0 and maven central shows me a 1.3.1 dated from yesterday. Do I just need to wait a while for maven central to update? Sorry to be a pain...

**Comment by pietermartin** [comment]
Ah damm, sorry `1.3.1`

**Comment by JPMoresmau** [comment]
Closing, solved by 1.3.1...
